## 2019/09/17 Homework 1

## Submit it by the end of 2019/09/23 on Blackboard.

## Grading: total 100 points.


### 1. Numpy Arrays:  14 points

In [116]:
import numpy as np

#Method -1:
zero1 = np.zeros(10,dtype=int)
print("Array of 10 zeros:")
print(zero1)
five1 = np.ones((10),dtype=int)*5
print("Array of 10 fives:")
print(five1)

#Method -2:
zero2 = np.full(10,0)
print("Array of 10 zeros:")
print(zero2)
five2 = np.full(10,5)
print("Array of 10 fives:")
print(five2)

Array of 10 zeros:
[0 0 0 0 0 0 0 0 0 0]
Array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]
Array of 10 zeros:
[0 0 0 0 0 0 0 0 0 0]
Array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


In [10]:
import numpy as np
array = np.random.random((3, 3, 3))
print("A 3x3x3 array with arbitary values:")
print(array)

A 3x3x3 array with arbitary values:
[[[0.95537418 0.81758215 0.05114544]
  [0.57809995 0.90916897 0.56682536]
  [0.09003148 0.65946283 0.24944107]]

 [[0.96662518 0.7850597  0.62342169]
  [0.49084208 0.51947981 0.15397978]
  [0.18566632 0.6519075  0.74913783]]

 [[0.56070805 0.25566241 0.27848238]
  [0.47553749 0.34505189 0.82508621]
  [0.1556269  0.14624245 0.99353809]]]


In [17]:
array = np.array([1,7,13,105,208])
print("The array is:",array)
print("The size of the array is:","%d bytes" % (array.size * array.itemsize))

The array is: [  1   7  13 105 208]
The size of the array is: 20 bytes


In [24]:
matrix = np.arange(10,22).reshape((3,4))
print("The 3x4 matrix filled with values from 10 to 21 are:")
print(matrix)

The 3x4 matrix filled with values from 10 to 21 are:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [117]:
matrix = np.full(16,1).reshape((4,4))
matrix = np.zeros((4, 4))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("The matrix is:")
print(matrix)

The matrix is:
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [123]:
print("Method-1")
array = [10, 20, 30]
print("Original array:")
print(array)
array_main= np.append(array, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(array_main)
print(" ")
#Method-2
print("Method-2")
array_new  = np.array([10,20,30])
array1 = np.array([40,50,60])
array2 = np.array([70,80,90])

final_arr =  np.hstack([array_new, array1,array2])
print("Original array:")
print(array)
print("After append values to the end of the array:")
print(final_arr)

Method-1
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
 
Method-2
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]



### 2. Create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements. 3 points


In [46]:
array = np.random.random(1000)
print("Mean is:")
mean = array.mean()
print(mean)
print("Standard deviation of the array elements:")
stan_dev = array.std()
print(stan_dev)
print("Variance of the array elements:")
var = array.var()
print(var)


Mean is:
0.5092323408554137
Standard deviation of the array elements:
0.28661649556247526
Variance of the array elements:
0.08214901552851439



### 3. Compute the trigonometric sine, cosine and tangent array of angles given in degrees. 3 points
   Sample degree: 0, 30, 45, 60, 90
   
Expected Output:
sine: array of angles given in degrees

[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01 6.12323400e-17]
tangent: array of angles given in degrees

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00 1.63312394e+16]

In [47]:
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### 4. Array Slicing: 5 questions, 20 points,4 points each
Given an array:
array([ 3,  6,  9,  25, 10,  8])

In [125]:
array = [ 3,  6,  9,  25, 10,  8]
print("All elements except first element :")
array[1:]

All elements except first element :


[6, 9, 25, 10, 8]

In [126]:
print("All elements except the last element :")
print(array[:5])

print("Alternate method : ")
print(array[0:-1])

All elements except the last element :
[3, 6, 9, 25, 10]
Alternate method : 
[3, 6, 9, 25, 10]


In [64]:
print("Every other element of the array from first element :")
array[::2]

Every other element of the array from first element :


[3, 9, 10]

In [129]:
print("Every element of the array from second element :")
print(array[1::2])

print("Alternate solution:")
print(array[1:])

Every element of the array from second element :
[6, 25, 8]
Alternate solution:
[6, 9, 25, 10, 8]


In [63]:
print("The reversed array is :")
array[::-1]

The reversed array is :


[8, 10, 25, 9, 6, 3]


### 5. Multidimensional Arrays: 4 questions, 20 points, 5 points each


In [73]:
multi = np.arange(0,32).reshape((8,4))
print("The multi-dimensional array is :")
multi

The multi-dimensional array is :


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [74]:
print("The array is :")
multi[0,2]=0
multi

The array is :


array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
print("The second column is :")
multi[:,[1]]

The second column is :


array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21],
       [25],
       [29]])

In [98]:
print("The 3x3 region from the above array is as shown below :")
multi_small=multi[:3,:3]
multi_small

The 3x3 region from the above array is as shown below :


array([[ 0,  1,  0],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### 6. Broadcasting: 40 points

1. Please add the following two arrays. You can reshape the array by np.reshape or 'newaxis'. (20 points)

In [92]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
final = a[:,np.newaxis] + b
print("The final array is :")
final

The final array is :


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [131]:
x = np.arange(4)
y = np.ones(5)
print(x)
print(y)
final = x[:,np.newaxis] + y
print("The final array is :")
print(final)

[0 1 2 3]
[1. 1. 1. 1. 1.]
The final array is :
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [108]:
#Using Numpy Broadcasting :
print("6*6 Time-Table matrix using numpy broadcasting :")
array_one=np.arange(1,7)
array_two=np.arange(1,7)
array_final = a[:,np.newaxis]*b
print(array_one)
print(array_two)
print(array_final)

6*6 Time-Table matrix using numpy broadcasting :
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [132]:
#Using Python Nested for-loop :
print("6*6 Time-Table matrix using Python nested for-loop :")
array_one=np.ones((6,6))
array_two=np.array([1,2,3,4,5,6])

for row in range(6):
    for column in range(6):
        array_one[row,column] = array_one[row,column]*array_two[row]
        array_one[row,column] = array_one[row,column]*array_two[column]
print(array_one)


6*6 Time-Table matrix using Python nested for-loop :
[[ 1.  2.  3.  4.  5.  6.]
 [ 2.  4.  6.  8. 10. 12.]
 [ 3.  6.  9. 12. 15. 18.]
 [ 4.  8. 12. 16. 20. 24.]
 [ 5. 10. 15. 20. 25. 30.]
 [ 6. 12. 18. 24. 30. 36.]]
